/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import Objetos.Libro;
import estructuras.ArbolB;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ADMIN
 */
public class NavegacionCategoria extends javax.swing.JFrame {

    /**
     * Creates new form NavegacionCategoria
     */
    public NavegacionCategoria() {
     initComponents();     this.setLocationRelativeTo(null); //centrar el jframe
        ImageIcon imagensa = new ImageIcon( "src/Imagenes/salir.png");
        Icon iconosa = new ImageIcon(imagensa.getImage().getScaledInstance(lblsalir.getWidth(),lblsalir.getHeight(),Image.SCALE_DEFAULT));
        lblsalir.setIcon(iconosa);     
        
        this.repaint();
        
        
     combo1.removeAllItems();combo2.removeAllItems(); ////////////////////////elimino items de cada combobox
     DefaultComboBoxModel modelo = new DefaultComboBoxModel ();
     ArrayList<String> datos=new ArrayList<>();
     datos=presentacion.Login.logueado.getAVL().getDatos();
         
     if (datos.size()>0){
            for (int i=0; i <= datos.size()-1;i++){
            modelo.addElement(datos.get(i));
         
        }}else{
      
     }
    
        combo1.setModel(modelo);
          
        
        
        
        
        
        
     // Accion a realizar cuando el JComboBox cambia de item seleccionado.
		combo1.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				jLabel4.setText(combo1.getSelectedItem().toString());
                                obtengoLibros(combo1.getSelectedItem().toString());
			}
		});   
        
        
    }
    
    
    public void obtengoLibros(String Cat){
            
     DefaultComboBoxModel modelo = new DefaultComboBoxModel ();
     
     
      ArbolB aux=new ArbolB(2);
      aux=presentacion.Login.logueado.getAVL().buscar(Cat).getArbolB();
     
      
      ArrayList <Libro> libros=new ArrayList<>();
     libros=aux.getLibros();
   
      
     if (libros.size()>0){
            for (int i=0; i <= libros.size()-1;i++){
            modelo.addElement(libros.get(i).getTitulo());
         
        }}else{
      
     }
    
        combo2.setModel(modelo);
        
        
        
        
    // Accion a realizar cuando el JComboBox cambia de item seleccionado.
		combo2.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				jLabel4.setText(combo2.getSelectedItem().toString());
                                      ArbolB aux=new ArbolB(2);
                                      
      aux=presentacion.Login.logueado.getAVL().buscar(Cat).getArbolB();
      ArrayList <Libro> libros=new ArrayList<>();
      libros=aux.getLibros();
                                             if (libros.size()>0){
                                               for (int i=0; i <= libros.size()-1;i++){
                                                if(libros.get(i).getTitulo().equals(combo2.getSelectedItem().toString())){
                                                Area1.setText("ISBN: "+libros.get(i).getISBN()+"\nAño: "+libros.get(i).getAnio()+"\nIdioma: "+libros.get(i).getIdioma()+"\nTitulo: "+libros.get(i).getTitulo()+"\nEditorial: "+libros.get(i).getEditorial()+"\nAutor: "+libros.get(i).getAutor()+"\nEdicion: "+libros.get(i).getEdicion()+"\nCategoria: "+libros.get(i).getCategoria()+"\nCarnet Propietario: "+libros.get(i).getPropietario()+"\n");
                                                }
         
                                               }}else{
      
                                             }
                                
                                
                                
                                
                                
                          
			}
		});        
          
    
    
    }
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo1 = new javax.swing.JComboBox();
        combo2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblsalir = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        getContentPane().add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 450, 30));

        combo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 450, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccionar Categoria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 234, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elegir Libro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 234, 26));

        lblsalir.setText("jLabel3");
        lblsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsalirMouseClicked(evt);
            }
        });
        getContentPane().add(lblsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 89, 64));

        jLabel4.setBackground(new java.awt.Color(0, 0, 153));
        jLabel4.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 380, 40));

        Area1.setBackground(new java.awt.Color(0, 0, 0));
        Area1.setColumns(20);
        Area1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        Area1.setForeground(new java.awt.Color(255, 255, 255));
        Area1.setRows(5);
        jScrollPane1.setViewportView(Area1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 320, 260));

        jLabel3.setBackground(new java.awt.Color(0, 0, 102));
        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Navegacion en Catalogo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 310, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoCategoria.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 900, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalirMouseClicked

          inicio principal=new inicio();
        principal.setVisible(true);
        
        this.dispose();        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_lblsalirMouseClicked

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NavegacionCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NavegacionCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NavegacionCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NavegacionCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NavegacionCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area1;
    private javax.swing.JComboBox combo1;
    private javax.swing.JComboBox combo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblsalir;
    // End of variables declaration//GEN-END:variables
}
